// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21. 3. 2026 16:19:37
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/plugins/**/*.{js,ts,mjs}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/composables/**/*.{js,ts,mjs}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/utils/**/*.{js,ts,mjs}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/holinec/Projects/github/pixeon-sro.github.io/grist/cenex/db/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;